### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by 7H3-5H4D0W**
I have once again updated the English translation of the Keyhub website by fixing grammar and spelling errors in the text. I also added the missing dash character that I left out by mistake.

### CODE REVIEW

**Review by jondycz — CHANGES_REQUESTED** [review]
GIVEAWAY_RESERVED_TLTP - Meaning of the message incorrectly changed

**Comment by 7H3-5H4D0W** [comment]
> GIVEAWAY_RESERVED_TLTP - Meaning of the message incorrectly changed

I made another quick update for the requested changes to fix the message meaning in the GIVEAWAY_RESERVED_TLTP part.

**Comment by jondycz** [comment]
> > GIVEAWAY_RESERVED_TLTP - Meaning of the message incorrectly changed
> 
> I made another quick update for the requested changes to fix the message meaning in the GIVEAWAY_RESERVED_TLTP part.

You have to create a new PR for that, since this one has already been merged. For future, please fork the repo, do all your changes and create PR after you're happy with the results instead of creating dozen of PRs in a week.

**Comment by 7H3-5H4D0W** [comment]
> > > GIVEAWAY_RESERVED_TLTP - Meaning of the message incorrectly changed
> > 
> > 
> > I made another quick update for the requested changes to fix the message meaning in the GIVEAWAY_RESERVED_TLTP part.
> 
> You have to create a new PR for that, since this one has already been merged. For future, please fork the repo, do all your changes and create PR after you're happy with the results instead of creating dozen of PRs in a week.

Well, thank you for your feedback and advice! I'm still learning the features of GitHub, and I will consider that suggestion in the future.

**Pull request merged**
