### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 7H3-5H4D0W**
I wrote a quick update to fix the spelling and grammar mistakes in this README.md file to make it look better.

### CODE REVIEW

**Review by jondycz — CHANGES_REQUESTED** [review]
Inconsistent capitalization: KeyHub
Consider using bbCode to create links

**Comment by 7H3-5H4D0W** [comment]
> Inconsistent capitalization: KeyHub Consider using bbCode to create links

I made another quick update for the requested changes to fix the inconsistent capitalization and used BBCode to create links in the text.

**Comment by jondycz** [comment]
> > Inconsistent capitalization: KeyHub Consider using bbCode to create links
> 
> I made another quick update for the requested changes to fix the inconsistent capitalization and used BBCode to create links in the text.

This has already been merged. You can't change the files.

**Comment by 7H3-5H4D0W** [comment]
> > > Inconsistent capitalization: KeyHub Consider using bbCode to create links
> > 
> > 
> > I made another quick update for the requested changes to fix the inconsistent capitalization and used BBCode to create links in the text.
> 
> This has already been merged. You can't change the files.

I know that already. I only made that comment for the record.

**Pull request merged**
